#!/bin/bash
# Studio Leish - Vercel Environment Setup
# Run: npx vercel env add

echo "=== Studio Leish - Vercel Environment Variables ==="
echo ""
echo "Add these in Vercel Dashboard: Project Settings → Environment Variables"
echo ""
echo "Required variables:"
echo ""
echo "1. BILLPLZ_API_KEY"
echo "   Get from: https://www.billplz.com/signin → Settings → API Keys"
echo "   Value: Your Billplz API key"
echo ""
echo "2. BILLPLZ_COLLECTION_ID"
echo "   Get from: https://www.billplz.com/go/collections"
echo "   Value: Your collection ID"
echo ""
echo "3. SUPABASE_URL"
echo "   Value: https://kcmoibrqyrzueslaqtgc.supabase.co"
echo ""
echo "4. SUPABASE_SERVICE_ROLE_KEY"
echo "   Get from: Supabase Dashboard → Settings → API"
echo "   Value: Your service role key (keep secret!)"
echo ""
echo "=== OR use Vercel CLI ==="
echo "vercel env add BILLPLZ_API_KEY production"
echo "vercel env add BILLPLZ_COLLECTION_ID production"
echo "vercel env add SUPABASE_URL production"
echo "vercel env add SUPABASE_SERVICE_ROLE_KEY production"
echo ""