-- Studio Leish Admin - Supabase Schema

-- Enable Row Level Security
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

-- Allow public read/write access (for admin panel)
GRANT ALL ON bookings TO anon, authenticated, service_role;
GRANT ALL ON clients TO anon, authenticated, service_role;
GRANT ALL ON site_settings TO anon, authenticated, service_role;

-- Bookings table
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id TEXT UNIQUE,
  client_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  room TEXT NOT NULL,
  booking_date DATE NOT NULL,
  booking_time TEXT NOT NULL,
  session_type TEXT DEFAULT 'Solo',
  total_amount DECIMAL(10,2) DEFAULT 0,
  status TEXT DEFAULT 'pending',
  payment_status TEXT DEFAULT 'pending',
  bill_id TEXT,
  rating INTEGER,
  notes TEXT,
  review_comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Clients table
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Site settings table (for image slots, etc.)
CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_bookings_date ON bookings(booking_date);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_payment ON bookings(payment_status);
CREATE INDEX IF NOT EXISTS idx_clients_email ON clients(email);

-- Insert sample site settings
INSERT INTO site_settings (key, value) VALUES
  ('slot_hero', ''),
  ('slot_gallery_1', ''),
  ('slot_gallery_2', ''),
  ('slot_gallery_3', ''),
  ('slot_gallery_4', ''),
  ('slot_service_1', ''),
  ('slot_service_2', ''),
  ('slot_service_3', '')
ON CONFLICT (key) DO NOTHING;